### ISSUE TITLE
failed to run migration file

### ISSUE THREAD

**Issue by longthanhtran** [Tigrov/yii2-pgsql-audit#1]
I am using yii2 2.0.22 and when I install yii2-pgsql-audit with composer, the extensions.php file section of this package has incorrect setup for bootstrap

```
'tigrov/yii2-pgsql-audit' => 
  array (
    'name' => 'tigrov/yii2-pgsql-audit',
    'version' => '1.3.3.0',
    'alias' => 
    array (
      '@tigrov/pgsql/audit' => $vendorDir . '/tigrov/yii2-pgsql-audit/src',
    ),
    'bootstrap' => 'tigrov\\pgsql\\audit\\Bootstrap',
  ),
```

while it should be like this 

```
'tigrov/yii2-pgsql-audit' => 
  array (
    'name' => 'tigrov/yii2-pgsql-audit',
    'version' => '1.3.3.0',
    'alias' => 
    array (
      '@tigrov/pgsql/audit' => $vendorDir . '/tigrov/yii2-pgsql-audit/src',
    ),
    array (
      'bootstrap' => 'tigrov\\pgsql\\audit\\Bootstrap',
    ),
  ),
```

One more thing, when I run ./yii migrate then nothing happen, so I suspect the migration file was not copy to the projects `migrations` folder.

Can you please help to review? Thanks

**Comment by longthanhtran** [comment]
It is my bad with above array ( .. ) section inside extensions.php, now when I visit `Boostrap.php` of yii2-pgsql-audit, it fall to map the migration to app scope, I think. So for now I still don't understand how the map can be made to external migrations folder / scope.

Edit. the error log likes this

```
Exception 'yii\base\InvalidConfigException' with message 'Object configuration must be an array containing a "class" element.'
```

**Comment by Tigrov** [comment]
Hi. Try to setup `MigrateController` in `console/config/main.php`:
```php
return [
    ...
    'controllerMap' => [
        'migrate' => [
            'class' => 'yii\console\controllers\MigrateController'
            'migrationPath' => '@console/migrations',
        ],
    ],
    ...
];
```

**Comment by longthanhtran** [comment]
Hi Tigrov,

Thanks for your reply, and I can't find the `console/config/main.php` but `config/console.php`. Therefore I try with 

```php
return [
    'bootstrap' => [
        // The component registers own console commands
    ],
    'components' => [
        'controllerMap' => [
            'migrate' => [
                'class' => 'yii\console\controllers\MigrationController',
                'migrationPath' => '@console/migrations',
            ],
        ],
    ]
];
```

and still have the same error log when running migration

**Comment by Tigrov** [comment]
Ok, try it
```php
return [
    ...
    'controllerMap' => [
        'migrate' => [
            'class' => 'yii\console\controllers\MigrationController',
        ],
    ],
    ...
];
```

Do not put it inside `'components' => []`

**Comment by longthanhtran** [comment]
yeah, that's I also realize just right after I post the comment, the `'controllerMap'`should stay on top level as your instruction. I also made the typo with MigrateController :D

```php
return [
...
    'controllerMap' => [
        'migrate' => [
            'class' => 'yii\console\controllers\MigrateController',
        ],
    ],
];
```

and it works perfectly. Might be the README update should help other users. Again, thank you very much 👍
